# "irc.freenode.net":
#     port: 6667
#     channels:
#       - "#marvin-testing"
#       - "#relayrelay"

"localhost":
    port: 6667
    channels:
      - "#webjam"
      - "#eotw"
      - "#general"