#!/usr/bin/env ruby

require 'rinda/ring'

puts ""
puts " Marvin Ring Server Status"
puts " ========================="
puts ""

begin
  DRb.start_service
  rs = Rinda::RingFinger.finger.lookup_ring(3)
  puts " Ring Server:        #{rs.__drburi}"
  items = rs.read_all([nil, nil, nil, nil])
  puts " Unprocessed Items:  #{items.size}"
  unless items.empty?
    puts ""
    start_time = items.first[2][:dispatched_at]
    puts  " Earliest Item:     #{start_time ? start_time.strftime("%I:%M%p %d/%m/%y") : "Never"}"
    end_time   = items.last[2][:dispatched_at]
    puts  " Latest Item:       #{end_time ? end_time.strftime("%I:%M%p %d/%m/%y") : "Never"}"
    mapping = {}
    items.each do |i|
      mapping[i[1].inspect] ||= 0
      mapping[i[1].inspect] += 1
    end
    width = mapping.keys.map { |k| k.length }.max
    puts ""
    puts " Unprocessed Message Counts:"
    puts " ---------------------------"
    mapping.each do |k, v|
      puts " #{k.ljust width}  => #{v}"
    end
  end
rescue Exception => e
  puts e.inspect
  puts " Ring server not running."
end

puts ""