#!/usr/bin/env ruby
require 'rubygems'

$:.unshift(File.dirname(__FILE__) + "/../lib/") if File.exist?(File.dirname(__FILE__) + "/../lib/marvin.rb")
MARVIN_ROOT = File.join(File.dirname(__FILE__), "..")

# And Require Marvin.
require 'marvin'
Marvin::Loader.run! :distributed_client
