#!/usr/bin/env ruby
require 'rubygems'
# Set the root of Marvin

if File.exist?(File.dirname(__FILE__) + "/../lib/marvin.rb")
  $:.unshift(File.dirname(__FILE__) + "/../lib/")
end

MARVIN_ROOT = File.join(File.dirname(__FILE__), "..")
# And Require Marvin.
require 'marvin'

trap "SIGINT" do
  Marvin::Loader.stop!
  exit
end

Marvin::Loader.run!